### ISSUE TITLE
Confusion about scoring

### ISSUE THREAD

**Issue by HenryDykhne** [dwave-examples/satellite-placement#9]
I'm new to some of these problems, and I think I might be missing something, but the way the score is calculated for coverage (by averaging the coverage of the satellites in each constellation) means that the sum of any 4 constellations that don't share satellites will be the same. Any solution ends up having the same score as any other provided satellites are not being shared. Is the algorithm not adding up the scores of each constellation? Or should the score for each constellation instead be calculated as:
1-product((1-satelite_coverage) for all satellites)?
implemented like this:
```
score = 1
for v in constellation:
    score *= (1-data['coverage'][str(v)])
score = 1-score
```
Under the current model of just taking the average, one could make a constellation worse by adding a satellite if it is bad enough. Is this intended? Am I missing something? Or is the calculation wrong in this example?

**Comment by mcfarljm** [comment]
Hi @HenryDykhne , you are correct: given how the sub-constellation coverage values are defined in the code, any solution that meets the constraints will have the same overall coverage score.  From that perspective, it does make the solution uninteresting, and I agree the formulation could be improved.  I suspect that the original intent of this example was more to illustrate the mechanics of solving this type of problem, where the general approach would be similar even if we had a more realistic way to define the coverage of each sub-constellation.

In the [Bass et al.](https://arxiv.org/abs/1709.05381) paper cited in the README, they mention sub-constellation coverage being defined as a percentage of time that a region is within range of at least one satellite.  Trying to represent something like that realistically (which would need to account not only for individual coverage but also redundancies/overlap) is probably outside of the scope of a simple example like this, but I do like your suggestion and think it alligns more closely with that definition in spirit.  And I believe it has the added benefit of eliminating the issue with all of the solutions being the same, since it defines sub-constellation coverage as a non-linear function of the individual coverages.

As you note, it should be an easy change.  Happy to review if you want to create a PR, although we'll need to make sure to update the description in the README accordingly.

**Comment by HenryDykhne** [comment]
I would be happy to author this PR but I don't appear to have write access to create branches. Am I perhaps missing something? @mcfarljm 
![image](https://user-images.githubusercontent.com/31970832/144694372-9fac5c57-198e-4b47-bae5-cec317865e5a.png)

**Comment by mcfarljm** [comment]
Great, thanks!  The best way to create the PR is to first create a fork of the repo (there should be a button for this in the top-right of the GitHub page).  Then you can clone your fork as a local working copy (alternatively, you can also add your fork as a new remote to your existing local copy).  From there, you can create a branch and push your new branch to your fork (and since it's your fork, you will have write access).  Then you can create a pull request for that branch of your fork (once you click on Pull Request in GitHub, it will probably detect that you pushed a new branch and suggest that as the source for the PR).

**Comment by HenryDykhne** [comment]
I have created the pr here:
https://github.com/dwave-examples/satellite-placement/pull/10

Please give it a look when you have time.

**Comment by HenryDykhne** [comment]
My PR has been merged, so I am closing this issue.
